<?php

return [
    \Styde\Form\View\Components\Form::class => 'form',
    \Styde\Form\View\Components\FormGroup::class => 'form-group',
    \Styde\Form\View\Components\Label::class => 'label',
    \Styde\Form\View\Components\Help::class => 'help',
    \Styde\Form\View\Components\Feedback::class => 'feedback',
    \Styde\Form\View\Components\Fields\Inputs\Input::class => 'input',
    \Styde\Form\View\Components\Fields\Inputs\Text::class => 'input-text',
    \Styde\Form\View\Components\Fields\Inputs\Number::class => 'input-number',
    \Styde\Form\View\Components\Fields\Inputs\Password::class => 'input-password',
    \Styde\Form\View\Components\Fields\Inputs\Email::class => 'input-email',
    \Styde\Form\View\Components\Fields\Inputs\Url::class => 'input-url',
    \Styde\Form\View\Components\Fields\Inputs\Search::class => 'input-search',
    \Styde\Form\View\Components\Fields\Inputs\File::class => 'input-file',
    \Styde\Form\View\Components\Fields\Inputs\Range::class => 'input-range',
    \Styde\Form\View\Components\Fields\Inputs\Textarea::class => 'textarea',
    \Styde\Form\View\Components\Fields\Selectables\Select::class => 'select',
    \Styde\Form\View\Components\Fields\Selectables\SelectMultiple::class => 'select-multiple',
    \Styde\Form\View\Components\Fields\Selectables\Radio::class => 'radio',
    \Styde\Form\View\Components\Fields\Selectables\RadioMultiple::class => 'radio-multiple',
    \Styde\Form\View\Components\Fields\Selectables\Checkbox::class => 'checkbox',
    \Styde\Form\View\Components\Fields\Selectables\CheckboxMultiple::class => 'checkbox-multiple',
    \Styde\Form\View\Components\Fields\Selectables\Switche::class => 'switch',
    \Styde\Form\View\Components\Fields\Selectables\SwitcheMultiple::class => 'switch-multiple',
    \Styde\Form\SubmitButton::class => 'submit',
];
